# mappings to filter dataframes before creating the database
mappings = {
    "ContractFolderID": "ContractFolderId",
    "updated": "Updated",
    "ContractFolderStatusCode": "ContractFolderStatusCode",
    "LocatedContractingParty.Party.PartyName.Name": "ContractingPartyName",
    "LocatedContractingParty.Party.PartyIdentification.ID": "ContractingPartyId",
    "LocatedContractingParty.ActivityCode": "ContractingPartyActivityCode",
    "LocatedContractingParty.Party.PostalAddress.CityName": "ContractingPartyCity",
    "LocatedContractingParty.Party.PostalAddress.PostalZone": "ContractingPartyZipCode",
    "LocatedContractingParty.Party.PostalAddress.Country.IdentificationCode": "ContractingPartyCountry",
    "LocatedContractingParty.Party.Contact.Telephone": "ContractingPartyTelephone",
    "LocatedContractingParty.Party.Contact.ElectronicMail": "ContractingPartyEmail",
    "ProcurementProject.Name": "ProcurementProjectName",
    "ProcurementProject.BudgetAmount.TaxExclusiveAmount": "ProcurementProjectTaxExclusiveAmount",
    "ProcurementProject.BudgetAmount.EstimatedOverallContractAmount": "ProcurementProjectEstimatedOverallAmount",
    "ProcurementProject.TypeCode": "ProcurementProjectTypeCode",
    "ProcurementProject.SubTypeCode": "ProcurementProjectSubTypeCode",
    "ProcurementProject.RequiredCommodityClassification.ItemClassificationCode": "ProcurementProjectCPVCode",
    "ProcurementProject.RealizedLocation.CountrySubentityCode": "ProcurementProjectRealizedCountry",
    "TenderingTerms.FundingProgramCode": "TenderingTermsFundingProgramCode",
    "TenderingTerms.AwardingTerms.AwardingCriteria.AwardingCriteriaTypeCode": "TenderingTermsAwardingCriteriaTypeCode",
    "TenderingProcess.ProcedureCode": "TenderingProcessProcedureCode",
    "TenderingProcess.SubmissionMethodCode": "TenderingProcessSubmissionMethodCode",
    "TenderingProcess.TenderSubmissionDeadlinePeriod.EndDate": "TenderingProcessEndDate",
    "TenderingProcess.TenderSubmissionDeadlinePeriod.EndTime": "TenderingProcessEndTime",
    "TenderResult.ResultCode": "TenderResultResultCode",
    "TenderResult.WinningParty.PartyIdentification.ID": "TenderResultWinningPartyId",
    "TenderResult.WinningParty.PartyName.Name": "TenderResultWinningPartyName",
    "TenderResult.AwardedTenderedProject.LegalMonetaryTotal.TaxExclusiveAmount": "TenderResultTaxExclusiveAmount",
    "TenderResult.AwardedTenderedProject.LegalMonetaryTotal.PayableAmount": "TenderResultPayableAmount",
    "TenderResult.SMEAwardedIndicator": "TenderResultSMEAwardedIndicator",
    "TenderResult.AwardDate": "TenderResultAwardDate",
}
