mappings = {
    "id": "ContractFolderID",
    "cp_name": "LocatedContractingParty.Party.PartyName.Name",
    "cp_id": "LocatedContractingParty.Party.PartyIdentification.ID",
    "cp_activity_code": "LocatedContractingParty.ActivityCode",
    "cp_city": "LocatedContractingParty.Party.PostalAddress.CityName",
    "cp_zip_code": "LocatedContractingParty.Party.PostalAddress.PostalZone",
    "cp_country": "LocatedContractingParty.Party.PostalAddress.Country.IdentificationCode",
    "cp_contact_telephone": "LocatedContractingParty.Party.Contact.Telephone",
    "cp_contact_email": "LocatedContractingParty.Party.Contact.ElectronicMail",
    "status": "ContractFolderStatusCode",
    "pp_name": "ProcurementProject.Name",
    "tender_funding": "TenderingTerms.FundingProgramCode",
    "pp_budget_amount_tax_exclusive": "ProcurementProject.BudgetAmount.TaxExclusiveAmount",
    "pp_budget_amount_est_overall_contract_amount": "ProcurementProject.BudgetAmount.EstimatedOverallContractAmount",
    "pp_type_code": "ProcurementProject.TypeCode",
    "pp_sub_type_code": "ProcurementProject.SubTypeCode",
    "cpv_code": "ProcurementProject.RequiredCommodityClassification.ItemClassificationCode",
    "pp_realized_location": "ProcurementProject.RealizedLocation.CountrySubentityCode",
    "tt_procedure_code": "TenderingProcess.ProcedureCode",
    "tt_awarding_criteria_code": "TenderingTerms.AwardingTerms.AwardingCriteria.AwardingCriteriaTypeCode",
    "tp_submission_method_code": "TenderingProcess.SubmissionMethodCode",
    "tp_deadline_date": "TenderingProcess.TenderSubmissionDeadlinePeriod.EndDate",
    "tp_deadline_time": "TenderingProcess.TenderSubmissionDeadlinePeriod.EndTime",
}
