# mappings to filter dataframes before creating the database
mappings = {
    "ContractFolderId": "ContractFolderID",
    "ContractFolderStatusCode": "ContractFolderStatusCode",
    "ContractingPartyName": "LocatedContractingParty.Party.PartyName.Name",
    "ContractingPartyId": "LocatedContractingParty.Party.PartyIdentification.ID",
    "ContractingPartyActivityCode": "LocatedContractingParty.ActivityCode",
    "ContractingPartyCity": "LocatedContractingParty.Party.PostalAddress.CityName",
    "ContractingPartyZipCode": "LocatedContractingParty.Party.PostalAddress.PostalZone",
    "ContractingPartyCountry": "LocatedContractingParty.Party.PostalAddress.Country.IdentificationCode",
    "ContractingPartyTelephone": "LocatedContractingParty.Party.Contact.Telephone",
    "ContractingPartyEmail": "LocatedContractingParty.Party.Contact.ElectronicMail",
    "ProcurementProjectName": "ProcurementProject.Name",
    "ProcurementProjectTaxExclusiveAmount": "ProcurementProject.BudgetAmount.TaxExclusiveAmount",
    "ProcurementProjectEstimatedOverallAmount": "ProcurementProject.BudgetAmount.EstimatedOverallContractAmount",
    "ProcurementProjectTypeCode": "ProcurementProject.TypeCode",
    "ProcurementProjectSubTypeCode": "ProcurementProject.SubTypeCode",
    "ProcurementProjectCPVCode": "ProcurementProject.RequiredCommodityClassification.ItemClassificationCode",
    "ProcurementProjectRealizedCountry": "ProcurementProject.RealizedLocation.CountrySubentityCode",
    "TenderingTermsFundingProgramCode": "TenderingTerms.FundingProgramCode",
    "TenderingTermsAwardingCriteriaTypeCode": "TenderingTerms.AwardingTerms.AwardingCriteria.AwardingCriteriaTypeCode",
    "TenderingProcessProcedureCode": "TenderingProcess.ProcedureCode",
    "TenderingProcessSubmissionMethodCode": "TenderingProcess.SubmissionMethodCode",
    "TenderingProcessEndDate": "TenderingProcess.TenderSubmissionDeadlinePeriod.EndDate",
    "TenderingProcessEndTime": "TenderingProcess.TenderSubmissionDeadlinePeriod.EndTime",
    "TenderResultResultCode": "TenderResult.ResultCode",
    "TenderResultWinningPartyId": "TenderResult.WinningParty.PartyIdentification.ID",
    "TenderResultWinningPartyName": "TenderResult.WinningParty.PartyName.Name",
    "TenderResultTaxExclusiveAmount": "TenderResult.AwardedTenderedProject.LegalMonetaryTotal.TaxExclusiveAmount",
    "TenderResultPayableAmount": "TenderResult.AwardedTenderedProject.LegalMonetaryTotal.PayableAmount",
    "TenderResultSMEAwardedIndicator": "TenderResult.SMEAwardedIndicator",
    "TenderResultAwardDate": "TenderResult.AwardDate",
}
