name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black
        pip install -e .

    - name: Format with black
      run: |
        black .

    - name: Lint with flake8
      run: |
        flake8 src tests --count --max-line-length=120 --statistics

    - name: Test with pytest
      run: |
        pytest tests/**/*.py
